format = """
[â•­](fg:line)\
$os\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$bun\
$deno\
$aws\
$cmd_duration\
$shell\
$time\
$username\
$line_break\
$character\
"""

palette = 'noctech'
add_newline = true

[palettes.noctech]
box = '#0f1417'          # muted frame/separators
background = '#1c2024' # neutral background
current_line = '#91cef5'    # accent line highlight
primary = '#ccc1e9'        # main accent for keys
foreground = '#dfe3e7'   # readable text values
gray = '#c1c7ce' # subtle secondary info
highlight = '#91cef5' # softer accent highlight
dim = '#0f1417'             # neutral dim tone
subtle = '#00344b'       # bright readable overlay

[os]
format = "(fg:current_line)[î‚¶](fg:gray)[$symbol ](fg:primary bg:gray)[î‚´](fg:gray)"
disabled = false
[os.symbols]
NixOS = "ïŒ“"

[directory]
format = "[â”€](fg:current_line)[î‚¶](fg:foreground)[ ](fg:primary bg:highlight)[î‚´](fg:foreground bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[î‚´](fg:box)"
home_symbol = "î­† ~/"
truncation_symbol = "î¯Ÿ "
truncation_length = 2
read_only = " "
read_only_style = ""

[git_branch]
format = "[â”€](fg:current_line)[î‚¶](fg:gray)[$symbol](fg:primary bg:gray)[î‚´](fg:gray bg:box)[ $branch](fg:foreground bg:box)"

[git_status]
format = "[( $all_status)](fg:foreground bg:box)[î‚´](fg:box)"

[nodejs]
format = "[â”€](fg:current_line)[î‚¶](fg:gray)[$symbol](fg:primary bg:gray)[î‚´](fg:gray bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)"

[bun]
format = "[â”€](fg:current_line)[î‚¶](fg:gray)[$symbol](fg:primary bg:gray)[î‚´](fg:gray bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)"
symbol = "ğŸ¥Ÿ"

[deno]
format = "[â”€](fg:current_line)[î‚¶](fg:gray)[$symbol](fg:primary bg:gray)[î‚´](fg:gray bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)"
symbol = "ğŸ¦•"

[aws]
format = "[â”€](fg:current_line)[î‚¶](fg:gray)[â˜ï¸](fg:primary bg:gray)[î‚´](fg:gray bg:box)[ $profile](fg:foreground bg:box)[î‚´](fg:box)"
symbol = "â˜ï¸"

[fill]
symbol = "â”"
style = "fg:current_line"

[cmd_duration]
min_time = 500
format = "[â”€](fg:current_line)[î‚¶](fg:dim)[ïƒ§ ](fg:primary bg:dim)[î‚´](fg:dim bg:box)[ $duration ](fg:foreground bg:box)[î‚´](fg:box)"

[shell]
format = "[â”€](fg:current_line)[î‚¶](fg:gray)[ï’‰ ](fg:primary bg:gray)[î‚´](fg:gray bg:box)[ $indicator](fg:foreground bg:box)[î‚´](fg:box)"
disabled = true

[time]
format = "[â”€](fg:current_line)[î‚¶](fg:gray)[ ](fg:primary bg:gray)[î‚´](fg:gray bg:box)[ $time](fg:foreground bg:box)[î‚´](fg:box)"
time_format = "%H:%M"
disabled = false

[username]
format = "[â”€](fg:current_line)[î‚¶](fg:gray)[ã€ ](fg:primary bg:gray)[î‚´](fg:gray bg:box)[ $user](fg:foreground bg:box)[î‚´](fg:box)"
show_always = true

[character]
format = """
[â”‚](fg:current_line)
[â•°â”€$symbol](fg:current_line) """
success_symbol = "[îŠ…îŠ…](fg:#e4e4e4)"
error_symbol = "[îŠ…îŠ…](fg:#ff6666)"
